export const CHANGE_NAVBAR = 'CHANGE_NAVBAR';

export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const PREVIOUS_QUESTION = 'PREVIOUS_QUESTION';
export const NEXT_QUESTION = 'NEXT_QUESTION';

export const CHANGE_MARKS = 'CHANGE_MARKS'; 

export const CHANGE_ANSWER_SCREEN = 'CHANGE_ANSWER_SCREEN';
export const CHANGE_PLANNING_SCREEN = 'CHANGE_PLANNING_SCREEN';

export const UPDATE_ANSWER_RECORD = 'UPDATE_ANSWER_RECORD';

export const RESET_TEST = 'RESET_TEST';
export const GO_TO_QUESTION = 'GO_TO_QUESTION';

export const RESET_SCREENS = 'RESET_SCREENS'


